#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "phpmyadmin"
name = "phpMyAdmin"
description.en = "Manage MySQL databases over the web"
description.fr = "Application web de gestion des bases de données MySQL"

version = "5.1.3~ynh1"

maintainers = ["julien"]

[upstream]
license = "GPL-2.0-only"
website = "http://www.phpmyadmin.net"
demo = "https://demo.phpmyadmin.net/master-config"
admindoc = "https://www.phpmyadmin.net/docs/"
code = "https://github.com/phpmyadmin/phpmyadmin"
cpe = "cpe:2.3:a:phpmyadmin:phpmyadmin"
fund = "https://www.phpmyadmin.net/donate/"

[integration]
yunohost = ">= 11.0.9"
architectures = "all"
multi_instance = false
ldap = true
sso = true
disk = "100M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/phpmyadmin"

[resources]
        [resources.sources.main]
        url = "https://files.phpmyadmin.net/phpMyAdmin/5.1.3/phpMyAdmin-5.1.3-all-languages.tar.gz"
        sha256 = "7a85454d82d88cc1a6beb09114a67fa40230c4eff2ae1778b434fa74e80dc6d7"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    [resources.apt]
    packages = "mariadb-server php8.2-xml, php8.2-curl, php8.2-zip, php8.2-mysql, php8.2-mbstring"

    [resources.database]
    type = "mysql"
