#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin = "john"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.209c11b5.name = "Upgrade from 5.1.1~ynh1"
    test_upgrade_from.fc4beaf1509ef346934094207ba5966538679b73.name = "Upgrade from 5.2.1~ynh1"
