test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin = "john"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.209c11b5.name = "Upgrade from 5.1.1~ynh1"
