#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
admin_user=$3

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a phpmyadmin
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Check that admin user is an existing account
sudo yunohost user list | python ../conf/user_list.py | grep "^$admin_user$" >/dev/null
if [[ ! $? -eq 0 ]]; then
    echo "Error : the chosen admin user does not exist"
    exit 1
fi

db_user=phpmyadmin
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')
sed -i "s@YNH_PMA_USER@$db_user@g" ../conf/create_db.sql
sudo yunohost app initdb $db_user -p $db_pwd
mysql -u root -p$(sudo cat /etc/yunohost/mysql) < ../conf/create_db.sql
mysql -u $db_user -p$db_pwd < ../conf/create_tables.sql
#mysql -u root -p$(sudo cat /etc/yunohost/mysql) < ../conf/create_tables.sql
sudo yunohost app setting phpmyadmin mysqlpwd -v $db_pwd

final_path=/var/www/phpmyadmin

# Copy files to the right place
sudo mkdir -p $final_path
sudo cp -r ../sources/* $final_path
sed -i "s@YNH_DOMAIN@$domain@g" ../conf/config.inc.php
sed -i "s@YNH_ADMIN_USER@$admin_user@g" ../conf/config.inc.php
sed -i "s@YNH_PMA_USER@$db_user@g" ../conf/config.inc.php
sed -i "s@YNH_PMA_PASSWORD@$db_pwd@g" ../conf/config.inc.php
sed -i "s@YNH_MYSQL_ROOT_PASSWORD@$(sudo cat /etc/yunohost/mysql)@g" ../conf/config.inc.php
sudo cp ../conf/config.inc.php $final_path

# Files owned by root, www-data can just read
sudo chown -R root: $final_path
sudo find $final_path -type f | xargs sudo chmod 644
sudo find $final_path -type d | xargs sudo chmod 755

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
nginxconf=/etc/nginx/conf.d/$domain.d/phpmyadmin.conf
sudo cp ../conf/nginx.conf $nginxconf
sudo chown root: $nginxconf
sudo chmod 600 $nginxconf

sudo service nginx reload
sudo yunohost app ssowatconf
