#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..."

# In older version, the admin setting was admin_user
if [ -z "$admin" ]; then
	admin=$(ynh_app_setting_get --app=$app --key=admin_user)
	ynh_app_setting_set --app=$app --key=admin --value=$admin
	ynh_app_setting_delete --app=$app --key=admin_user
fi

# If db_admin_user doesn't exist, create it
if [ -z "$db_admin_user" ]; then
	# Setup a privileged user for phpmyadmin (to prevent using MySQL root user)
	db_admin_user="${app}_root"
	ynh_app_setting_set --app=$app --key=db_admin_user --value=$db_admin_user
	db_admin_pwd="$(ynh_string_random)"
	ynh_app_setting_set --app=$app --key=db_admin_pwd --value=$db_admin_pwd

	if ! ynh_mysql_user_exists --user=$db_admin_user
	then
	  ynh_mysql_create_user $db_admin_user "$db_admin_pwd"
	  ynh_mysql_execute_as_root --sql="GRANT ALL PRIVILEGES ON *.* TO '$db_admin_user'@'localhost' IDENTIFIED BY '$db_admin_pwd' WITH GRANT OPTION;
	  FLUSH PRIVILEGES;" --database=mysql
	fi
fi

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=5

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --keep="config.inc.php" --full_replace=1
fi

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=3

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading PHP-FPM configuration..." --weight=4

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

#=================================================
# SPECIFIC UPGRADE
#=================================================
# UPGRADE THE DATABASE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading database..." --weight=2

	# Handle upgrade from a version before latest version
	# Ignore warnings and failures that will occur if already on latest version
	ynh_replace_string --match_string="phpmyadmin" --replace_string="$db_name" --target_file=$install_dir/sql/upgrade_column_info_4_3_0+.sql
	ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" \
		< $install_dir/sql/upgrade_column_info_4_3_0+.sql > /dev/null 2>&1 || true

	# Upgrade from last version (don't ignore failures)
	ynh_replace_string --match_string="phpmyadmin" --replace_string="$db_name" --target_file=$install_dir/sql/upgrade_tables_4_7_0+.sql
	ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" \
		< $install_dir/sql/upgrade_tables_4_7_0+.sql

	ynh_replace_string --match_string="phpmyadmin" --replace_string="$db_name" --target_file=$install_dir/sql/create_tables.sql
	ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" \
		< $install_dir/sql/create_tables.sql
fi

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Setup phpMyAdmin temporary folder
mkdir -p $install_dir/tmp
chown -R $app: $install_dir/tmp

#=================================================
# INSTALL DEPENDENCIES
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading dependencies with Composer..." --weight=19

	# Install Composer
	ynh_install_composer

	# Force dependency to the used PHP version
	ynh_exec_warn_less ynh_composer_exec --commands="config -g platform.php $YNH_PHP_VERSION"
	# Install dependencies
	ynh_exec_warn_less ynh_composer_exec --commands="update --no-dev"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
